### ISSUE TITLE
您好，请问是什么原因导致仅支持iOS？

### ISSUE THREAD

**Issue by mengxin-FE** [sanyuered/WeChat-MiniProgram-AR-AI-V2#1]
您好，请问是什么原因导致仅支持iOS？

**Comment by sanyuered** [comment]
1、目前除了支持iOS，也支持部分的华为手机。详细请见：https://zhuanlan.zhihu.com/p/544052686

2、个人猜测：iOS版使用了ARKit，而Android版不支持ARKit，所以无法使用AR。可以支持部分的华为手机，因为有华为AR Engine这个平台。
